version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres_temporary_user # change with configuration value
      POSTGRES_PASSWORD: postgres_temporary_password # change with configuration value
      POSTGRES_DB: transcendence
    networks:
      - transcendence
networks:
  transcendence:
