version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports:
      - $DATABASE_PORT:5432
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    networks:
      - transcendence
  test-db:
    image: postgres:latest
    ports:
      - $DATABASE_PORT_TEST:5432
    environment:
      POSTGRES_USER: $DATABASE_USER_TEST
      POSTGRES_PASSWORD: $DATABASE_PASSWORD_TEST
      POSTGRES_DB: $DATABASE_NAME_TEST
    networks:
      - transcendence
networks:
  transcendence:
